config/routes.rb
TestMongoid::Application.routes.draw do
  get "comment/create"

  resources :articles do
    resources :comments
  end
  root :to => 'articles#index'
end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes
  field :name
  field :content
  field :published_on, :type => Date
  validates_presence_of :name
  embeds_many :comments
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  field :name
  field :content
  embedded_in :article
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
  
  before_filter :init_comment, :only => [:show, :create, :update]
  
private
  
  def init_comment
    @comment = Comment.new
  end
    
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  belongs_to :article
  actions :create, :destroy
  respond_to :js
  layout false
  
  def create
    create! do |success, failure|
      failure.js { render :new }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def e params
    escape_javascript params
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/articles/_comments.html.erb
<div class='comments'>
  <h2>Comments</h2>
  <% @article.comments.each do |comment| %>
    <%= render comment %>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <%= render '/shared/error_explanation', :object => @article %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br />
    <%= f.date_select :published_on %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Published</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.name %></td>
      <td><%= article.content %></td>
      <td><%= article.published_on %></td>
      <td><%= link_to 'Show', article %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <b>Name:</b>
  <%= @article.name %>
</p>

<p>
  <b>Published:</b>
  <%= @article.published_on %>
</p>

<p>
  <b>Content:</b>
  <%= @article.content %>
</p>

<%= render 'comments' %>

<h2>New Comment</h2>
<%= render '/comments/new_form', :comment => @comment %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <h3><%= comment.name %></h3>
  <p><%= comment.content %></p>
  <p><%= link_to 'Delete', article_comment_path(@article, comment), :method => :delete, :confirm => 'Are you sure?', :remote => true %></p>
</div>

app/views/comments/_new.html.erb
<%= form_for [@article, @comment ||= Comment.new], :remote => true do |f| %>
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <p><%= f.label :name %> <%= f.text_field :name %></p>
  <p><%= f.text_area :content, :rows => 10 %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/_new_form.html.erb
<%= form_for [@article, comment], :remote => true do |f| %>
  <%= render '/shared/error_explanation', :object => comment %>

  <p><%= f.label :name %> <%= f.text_field :name %></p>
  <p><%= f.text_area :content, :rows => 10 %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/create.js.erb
$('#notice').html('<%= notice%>');
$('.comments').append("<%= e render @comment %>");
$('#new_comment').replaceWith("<%= e render('/comments/new_form', :comment => Comment.new) %>")

app/views/comments/create_errors.js.erb
$('#new_comment').replaceWith("<%= e render '/comments/new' %>");
$('#notice').html('');

app/views/comments/destroy.js.erb
$('#notice').html('<%= notice%>');
$("#comment_<%= @comment.id%>").remove();

app/views/comments/new.js.erb
$('#new_comment').replaceWith("<%= e render '/comments/new_form', :comment => @comment %>");
$('#notice').html('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestMongoid</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_explanation.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name.downcase %> from being saved:</h2>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end -%>